### ISSUE TITLE
js file link 

### ISSUE THREAD

**Issue by usama78621** [teamsnap/teamsnap-ui#1389]
How to link JS file in TeamSnap-UI using CDN or NPM

**Comment by bradcypert** [comment]
Hey @usama78621, you should be able to use npm to install this package and then import it using whatever module resolver you're using (babel, for example). These are definitely components and not simply scripts, so to really benefit from them, you'd need to be using React.

In a full project, you'd likely use create-react-app to create a new react app, then add teamsnap ui to your package.json, and then run `npm i`. Then you'd import the components that you want to use into your project and use them there!

If you're running into specific issues, can you create a demo repository showing the issue you're seeing? It'll help me help you :)

**Comment by usama78621** [comment]
hey when we use popups and modals and other element funcationalions work I
try many times but the teamsnap-ui website works well
I using cdn Link css like bootstrap but I can't find the js file please
provide  the proper way to use this on the website
thanks

**Comment by bradcypert** [comment]
Many of the modals and popups are CSS based. Unfortunately there isn't a JavaScript script to pull in directly. You're expected to pull this in as a library and build your application with it via importing and using components.
