### ISSUE TITLE
Should we add plain HTML examples into storybook or keep it React specific?

### ISSUE THREAD

**Issue by bradcypert** [teamsnap/teamsnap-ui#360]
Currently we have the UI Patterns library (code internal, dist publicly accessible) that helps model how to use TeamSnap UI with plain HTML, CSS, and minimal JavaScript. This library is the SCSS and JavaScript code for using TeamSnap UI with React. Let's use this issue to discuss if we want to keep UI Patterns around and if not, to discuss if we want to find a way to use plain HTML with storybook to port that functionality over.

**Comment by saralohr** [comment]
I think Storybook does support an HTML output display - maybe via an add-on. Can't remember if it's out of the box or not.

The other thing I like about UI Patterns is the ability to prototype in a sandbox with our patterns: https://teamsnap-ui-patterns.netlify.app/sandbox.html

However, I'm pretty sure I'm the only one that actually uses that feature and I bet you could do essentially the same thing in Storybook just with a story for whatever design exploration is being done.

My previous employer (we created the Drizzle tool that UI Patterns is built on based on our own needs for pattern libraries) recently switched to Storybook which got me thinking about it:

https://cloudfour.com/thinks/from-drizzle-to-storybook/
