### ISSUE TITLE
Our TypeScript code needs a linter

### ISSUE THREAD

**Issue by bradcypert** [teamsnap/teamsnap-ui#691]
We have a fair amount of inconsistency between fundamental syntax choices with TeamSnap UI. Ideally, we can setup a linter configuration and address the inconsistencies.

**Comment by bradcypert** [comment]
@BillyFigueroa Any suggestions on a linter configuration for a baseline? I know this is an area that you're passionate about, so I'd love for you to lead this one if you'd like to :)

**Comment by BillyFigueroa** [comment]
Still working on this
